
version: '3.3'
services:

  website:
    ports:
      - 8000:8000

  back:
    build:
      context: ./back
      target: base
    command: pnpm dev
    volumes:
      # Mount source code to restart app on change
      - ./back/src:/app/src
      - ./back/nodemon.json:/app/nodemon.json
    ports:
      - 8001:8001
      - 9000:9000
    environment:
      - NODE_ENV=
      - LOGLEVEL=debug

  captionsdb:
    volumes: 
      - 'captionsdb:/data/db'

volumes: 
  captionsdb:
    external: true
